Issue 299
tranquilitybase-io/tb-gcp pull request #397
Opened 2020-07-09 13:03 UTC by adamgft

## PR Type  
What kind of change does this PR introduce?  
  
Please check the boxes that applies to this PR.  
  
- [ ] Bugfix  
- [ X ] Feature  
- [ ] Code style update (formatting, local variables)  
- [ ] Refactoring (no functional changes, no api changes)  
- [ ] Build related changes  
- [ ] CI related changes  
- [ ] Documentation content changes  
- [ ] TranquilityBase application / infrastructure changes  
- [ ] Other... Please describe:  

## Purpose 
Full purpose found in ticket #299

Notiable changes: Due to the TB development environment logging will be enabled at the folder level. This can later be moved to the organisation level with little refactoring if needed.

To enable Audit logging for Admin read/write operations at the TB folder level and create a aggregated sink to export the logs to a storage bucket within the telemetry project.
  
## Testing

Deploy:
![terraformdeploy](https://user-images.githubusercontent.com/66415638/87043018-5faf7b80-c1ec-11ea-8989-66f93165fff9.PNG)

Sink:
![Sink](https://user-images.githubusercontent.com/66415638/87043048-6938e380-c1ec-11ea-9a4b-81796ecbf860.PNG)

Admin Write Log:
![AdminWriteLog](https://user-images.githubusercontent.com/66415638/87043085-7786ff80-c1ec-11ea-9aaf-1e3412367a45.PNG)

Admin Read Log:
![AdminReadLog](https://user-images.githubusercontent.com/66415638/87043100-7bb31d00-c1ec-11ea-95d3-d9c3a812caff.PNG)

## Reviewers  
 - **Reviewer A** please review this part.  
 - **Review B** please review this part.  
  
  ## Checklist  
 - [ X ] This PR is linked to one or more issues.  
 - [ X ] This PR has been tested (attach evidence if possible).  
 - [ X ] This PR has passed style guidelines.

2020-08-08 14:06 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  default     = "roles/storage.objectCreator"
I'm wondering if this needs to be a variable at all. Do you foresee GCP changing their ways and allowing a sink for or less permissions than a `roles/storage.objectCreator`? I don't because that would entail breaking every audit log sink already deployed out there.

Nonetheless, the naming suggestion would be:
- name: `log_sink_writer_bucket_iam_role`
- description: `Role required by the log sink writer when writing into a bucket. The default should not be changed.`

2020-08-08 14:23 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  source = "github.com/tranquilitybase-io/terraform-google-cloud-storage.git?ref=v1.6.0-logging"
When creating a single bucket
`github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=v1.6.0-logging`
is a better module than
`github.com/tranquilitybase-io/terraform-google-cloud-storage.git?ref=v1.6.0-logging`
specially when defining the bucket name.

2020-08-08 14:24 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
If the `github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=v1.6.0-logging` module is used, you shouldn't need this variable anymore.

2020-08-11 15:21 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "audit log bucket life cycle to move data into nearline before being deleted"
As tranquillity base's development environment shares the same org, the following logging has been enabled on the root tb folder level rather than at a org level. So I've selected the following naming scheme off your suggestion: 

- name: `root_folder_audit_log_bucket_lifecycle_rules`
- description: `root folder audit log bucket lifecycle rules. Defaults to moving from standard to nearline after 30 days and deleting after 365.`

2020-08-11 15:24 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
As tranquillity base's development environment shares the same org, the following logging has been enabled on the root tb folder level rather than at a org level. So I've selected the following naming scheme off your suggestion: 

- name: `root_folder_audit_log_sink_name`
- description: `root folder audit log sink name`
- default: ` root-folder-audit-log-sink-name`

2020-08-12 08:13 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
As tranquillity base's development environment shares the same org, the following logging has been enabled on the root tb folder level rather than at a org level. So I've selected the following naming scheme off your suggestion:

- name: `root_folder_audit_log_bucket_labels`
- description: `root folder audit log bucket labels`

2020-08-12 08:15 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
As tranquillity base's development environment shares the same org, the following logging has been enabled on the root tb folder level rather than at a org level. So I've selected the following naming scheme off your suggestion:

- name: `root_folder_audit_log_bucket_prefix`
- description: `root folder audit log bucket name prefox`
- default: `root-folder`

2020-08-12 08:16 UTC, adamgft commented on tb-marketplace/tb-config-creator/tb-config-creator
> +rm rootfolderiampolicy.yaml
Implemented changes

2020-08-12 08:17 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
Implemented changes

2020-08-12 08:17 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
Implemented changes

2020-08-12 08:19 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
Myself and Chris were running into issues with this module causing it to crash Terraform when providing the LifeCycle rules so switched to using terraform-google-modules/cloud-storage/google which seems to be more stable.

2020-08-12 08:20 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  source = "github.com/tranquilitybase-io/terraform-google-cloud-storage.git?ref=v1.6.0-logging"
Myself and Chris were running into issues with this module causing it to crash Terraform when providing the LifeCycle rules so switched to using terraform-google-modules/cloud-storage/google which seems to be more stable.

2020-08-14 14:26 UTC, arvindclement commented
Before you merge I would just wait for Ricardo to give the final go ahead so reach out to him first thing Monday morning

2020-08-17 21:10 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  source = "github.com/tranquilitybase-io/terraform-google-cloud-storage.git?ref=v1.6.0-logging"
Implemented changes

2020-08-17 21:10 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
Implemented changes

2020-08-25 08:42 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "region for audit log bucket"
changed to "location for tb folder admin read/write bucket audit logs"

2020-08-25 08:43 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +variable "audit_bucket_name" {
Changed to "tb_folder_admin_rw_audit_log_bucket_name"

2020-08-25 08:44 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "storage class for the bucket"
Changed name to : tb_folder_admin_rw_audit_log_bucket_storage_class
Changed des to: storage class for tb folder admin read/write bucket audit logs

2020-08-25 08:45 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "main audit log bucket name"
changed name to : tb_folder_admin_rw_audit_log_bucket_name
changed des to : bucket name for tb folder admin read/write bucket audit logs

2020-08-25 08:46 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "root folder audit log bucket lifecycle rules. Defaults to moving from standard to nearline after 30 days and deleting after 365."
Changed to tb_folder_admin_rw_audit_log_bucket_lifecycle_rules to add clarity

2020-08-25 08:46 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "root folder audit log sink name"
Changed to tb_folder_admin_rw_audit_log_sink_name to add clarity

2020-08-25 08:47 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +  description = "include logs for folders and project below folder specified"
Changed des to "include logs for folders and project below the tb folder"

2020-09-01 11:56 UTC, rjmco requested changes

2020-09-01 11:56 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  filter           = "logName=(folders/${var.root_id}/logs/cloudaudit.googleapis.com%2Factivity OR folders/${var.root_id}/logs/cloudaudit.googleapis.com%2Fdata_access)"
This should at least be:

```
logName:("/logs/cloudaudit.googleapis.com%2Factivity" OR "/logs/cloudaudit.googleapis.com%2Fdata_access")
```

to make sure we don't filter out the children logs.

However, I am still not sure if we should restrict the filter further. Let's have a chat.

2020-09-01 18:16 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  filter           = "logName=(folders/${var.root_id}/logs/cloudaudit.googleapis.com%2Factivity OR folders/${var.root_id}/logs/cloudaudit.googleapis.com%2Fdata_access)"
So... according to https://cloud.google.com/logging/docs/audit#viewing_audit_logs we are also missing `system_event` on the filter, therefore it should be:

```
logName:(
  "/logs/cloudaudit.googleapis.com%2Factivity" OR
  "/logs/cloudaudit.googleapis.com%2Fdata_access" OR
  "/logs/cloudaudit.googleapis.com%2Fsystem_event"
)

2020-09-17 11:25 UTC, Waterhouse-GFT approved these changes
Looks good to me.

2020-09-17 16:26 UTC, adamgft commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  filter           = "logName=(folders/${var.root_id}/logs/cloudaudit.googleapis.com%2Factivity OR folders/${var.root_id}/logs/cloudaudit.googleapis.com%2Fdata_access)"
implemented and tested

2020-09-29 14:54 UTC, rjmco requested changes
Apologies for the delay. I just needed a clarification on `tb-config-creator`'s L192 change. Please read the remaining in-line comments.

2020-10-09 08:15 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  source = "github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=logging"
It seems one of the recent google provider upgrades broke our `github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=logging` because the `is_live` parameter has been depercate as announced on https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#is_live-is-now-removed

This breaks the image creation with the following error:

```
Step #0 - "Package image": ==> googlecompute: Error: Unsupported argument
Step #0 - "Package image":     googlecompute: Warning: Attribute is deprecated
Step #0 - "Package image": ==> googlecompute:
Step #0 - "Package image": ==> googlecompute:   on .terraform/modules/audit-log-bucket/modules/simple_bucket/main.tf line 63, in resource "google_storage_bucket" "bucket":
Step #0 - "Package image":     googlecompute:
Step #0 - "Package image":     googlecompute:   on .terraform/modules/gcs_bucket_logging/modules/simple_bucket/main.tf line 22, in resource "google_storage_bucket" "bucket":
Step #0 - "Package image": ==> googlecompute:   63:         is_live               = lookup(lifecycle_rule.value.condition, "is_live", null)
Step #0 - "Package image":     googlecompute:   22:   bucket_policy_only = var.bucket_policy_only
Step #0 - "Package image": ==> googlecompute: 
Step #0 - "Package image": ==> googlecompute: An argument named "is_live" is not expected here.
```

The upstream terraform module has already been fixed as https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/89 points out but a release with the fix has not come through yet, which means that we need to rebase our `github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=logging-v2` with the new upstream `master` and create a `logging-v3` branch and reference it here.

2020-10-09 09:01 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  filter           = "logName:(/logs/cloudaudit.googleapis.com%2Factivity OR /logs/cloudaudit.googleapis.com%2Fdata_access OR /logs/cloudaudit.googleapis.com%2Fsystem_event)"
Please take into consideration https://github.com/tranquilitybase-io/tb-gcp/issues/299#issuecomment-706044130

2020-10-09 09:43 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/main.tf
> +  source = "github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=logging"
`github.com/tranquilitybase-io/terraform-google-cloud-storage.git//modules/simple_bucket?ref=logging-v3` is now available.

2020-10-09 12:15 UTC, rjmco approved these changes
@adamgft thanks for all the work. I've squashed your commits and added one with my QC changes. All is tested and working. LGTM.

2020-10-09 12:15 UTC, merged