Issue 375
tranquilitybase-io/tb-gcp pull request #408
Opened 2020-07-20 10:12 UTC by Waterhouse-GFT

## PR Type  
What kind of change does this PR introduce?  
  
Please check the boxes that applies to this PR.  
  
- [ ] Bugfix  
- [x] Feature  
- [ ] Code style update (formatting, local variables)  
- [ ] Refactoring (no functional changes, no api changes)  
- [ ] Build related changes  
- [ ] CI related changes  
- [ ] Documentation content changes  
- [ ] TranquilityBase application / infrastructure changes  
- [ ] Other... Please describe:  

## Purpose 
Adds a labelling module to TB. Adds deploy_owner and org name labels to shared projects for cost and ownership tracking.
Adds gcloud commands and parsing to tb-welcome to add owner to top level deploy folder.
 https://github.com/tranquilitybase-io/tb-gcp/issues/375
## Reviewers  
 - **Reviewer A** please review this part.  
 - **Review B** please review this part.  
  
  ## Checklist  
 - [x] This PR is linked to one or more issues.  
 - [x] This PR has been tested (attach evidence if possible).  
![image](https://user-images.githubusercontent.com/64899361/87926547-c00aac80-ca79-11ea-995c-acdd0bd941f2.png)

 - [ ] This PR has passed style guidelines.

2020-07-21 09:00 UTC, alexdgft commented on tb-marketplace/tb-config-creator/tb-config-creator
> +#Explicit labelling is required here because Terraform has not been appl
Typo?

2020-07-21 09:01 UTC, alexdgft commented on tb-gcp-tr/landingZone/tb-welcome
> +
Remove extra new lines

2020-07-21 09:01 UTC, alexdgft commented on tb-gcp-tr/shared-projects-creation/main.tf
> +
Remove extra new lines

2020-07-21 09:02 UTC, alexdgft commented on tb-gcp-tr/shared-projects-creation/main.tf
> +
Remove extra new lines

2020-07-21 09:02 UTC, alexdgft commented on tb-gcp-tr/shared-projects-creation/variables.tf
> +
Remove extra new lines

2020-07-21 09:02 UTC, alexdgft commented on tb-marketplace/tb-config-creator/tb-config-creator
> +
Remove extra new lones

2020-07-21 12:38 UTC, MatStacey commented on tb-gcp-tr/bootstrap/files/bootstrap.sh
> +deploy_owner = ${deploy_owner}
is there a reason ${deploy_owner} is not wrapped in quotes and the rest of the values are?

2020-08-03 16:20 UTC, Waterhouse-GFT commented on tb-gcp-tr/landingZone/no-itop/input.tfvars
> +labels={"deployed_by":"dbv","client":"clv","created_by":"","cost_centre":"","business_unit":"","solution_id":"","team":"tranquilitybase","environment":""}
The other labels were added after talking with @scottholmangft, so that they match what are attached to ec.

2020-08-03 16:35 UTC, Waterhouse-GFT commented on tb-gcp-tr/landingZone/tb-welcome
> +deployed_by=$(gcloud projects list --filter PROJECT_ID=${PROJECT_ID} --format="json(labels.deployed_by)" | sed -E 's/\},\s*\{/\},\n\{/g' ${deployed_by} | grep  '"deployed_by"' | cut -d ":" -f2)
Config-creator is what initally gets the label value, tb welcome pulls the label value to pass into the project being deployed.

2020-08-07 08:17 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/variables.tf
> +}
run a `terraform fmt`

2020-08-07 08:20 UTC, rjmco commented on tb-gcp-tr/landingZone/tb-welcome
> +,created_by = "${deployed_by}"
this comma is not necessary on HCL.

2020-08-07 08:30 UTC, rjmco commented on tb-marketplace/tb-dep-manager/tranquility-base.jinja
> +        deploy_owner="{{ deploy_owner }}"
Here you expect a `deploy_owner` to exist but you are passing a `deployed_by`. Also, please check my previous comment.

2020-08-07 08:54 UTC, rjmco commented on tb-marketplace/tb-config-creator/tb-config-creator
> +  gcloud projects create "${PROJECT_ID}" --folder "${tb_folder_id}" --format=none --labels deployed_by="${ACTIVE_ACCOUNT}"
The optional fields are not being considered here. The custom labels should be extracted from `custom_labels.txt` and added to this command-line.

If you want to simplify this a bit, you can get rid of the `admin=${ADMIN}` part of the if and remove the command-line switch.

2020-08-18 15:25 UTC, rjmco commented on tb-gcp-tr/landingZone/tb-welcome
> +echo "}" >> labels.auto.tfvars
Line 28 destroys the `custom_labels.txt`'s contents including the comments that you are checking in on this PR and the user's edits which will later be uploaded into a Cloud Source Repository.

Taking into account that label keys and label values cannot have whitespaces as well as most special characters (heck, not even upper case characters are allowed; see `gcloud projects create --help` for more info) lines 25 to 34 above can be simplified into the following:

```
echo labels = { > labels.auto.tfvars 
gcloud projects describe ${PROJECT_ID} --format='value[delimiter=","](labels)' | tr -s "," "\n" | awk -F '=' '{ print $1 "=\"" $2 "\""}' >> labels.auto.tfvars
echo "}" >> labels.auto.tfvars
```

which as the added advantage of not destroying the `custom_labels.txt` file.

For more information on the `[delimiter=","]` syntax I used above, check `gcloud topic formats` it is one of those hidden `gcloud` gems.

2020-08-18 15:27 UTC, rjmco commented on tb-marketplace/tb-config-creator/tb-config-creator
> +#Explicit labelling is required here because Terraform has not been appllied.
typo: `applied`

2020-08-18 15:55 UTC, rjmco commented on tb-marketplace/tb-config-creator/tb-config-creator
> +  IFS=' ' read -ra customLabels < "$custom_labels_path"
Do you mean `IFS=','`? According to the `custom_labels.txt` file that you are checking in, the labels are to be comma separated and not space separated.

2020-08-18 16:36 UTC, Waterhouse-GFT commented
> 
> 
> Besides the in-line comments, I'm still waiting for your answer to the following question that I asked 15 days ago:
> 
> > Why are we ignoring labels changes? Does terraform attempt to re-create a project if google_project's labels parameter gets changed? I would expect terraform to be clever enough to simply update the labels on the deployed project without re-creating it. Did your testing prove my hunch/assumption wrong?

While terraform is smart enough to ignore changes, explicitly ignoring changes means that if the labels are edited outside of terraform, it does not get out of sync with the state file. Which would result in the resources being marked as tainted.

2020-08-18 16:50 UTC, rjmco commented
> > Besides the in-line comments, I'm still waiting for your answer to the following question that I asked 15 days ago:
> > > Why are we ignoring labels changes? Does terraform attempt to re-create a project if google_project's labels parameter gets changed? I would expect terraform to be clever enough to simply update the labels on the deployed project without re-creating it. Did your testing prove my hunch/assumption wrong?
> 
> While terraform is smart enough to ignore changes, explicitly ignoring changes means that if the labels are edited outside of terraform, it does not get out of sync with the state file. Which would result in the resources being marked as tainted.

Ok. Then question is, should `terraform` override manual modifications of project labels. I suppose the answer should be yes as that is a Infrastructure as Code best-practice. There needs to be a specific reason to not follow this best-practice.

2020-08-19 23:21 UTC, rjmco requested changes
Testing was successful with:
1. No custom labels;
2. One custom label;
3. Two custom labels.

However, testing also revealed that the `custom_labels.txt` file is misplaced. It should not be in the `tb-gcp-tr/landingZone/no-itop` folder as it is not used by the Terraform deployment on that folder, it should instead be placed on the `tb-marketplace/tb-config-creator` folder because it is used by the `tb-config-creator` script stored on that folder.

After the move, please update the `README.md` with an optional step on how to set custom labels using the `custom_labels.txt` file.

2020-08-19 23:21 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/custom_labels.txt
> +#Uncomment the above line to add custom labels, you can add upto 255 labels
Should be `Uncomment first line`.

Add: `Only labels on the first line will be considered. Labels on the lines below will be ignored.`

Typo: `upto`

2020-08-19 23:21 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/custom_labels.txt
> +#cost_centre=,business_unit=,team=,environment=,
typo: `cost_centre`

2020-08-19 23:21 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/custom_labels.txt
> +#Comma separated list of label KEY=VALUE pairs to associated with projects.
typo: `comma separated` (should have an hyphen)

2020-08-19 23:21 UTC, rjmco commented on tb-gcp-tr/landingZone/no-itop/custom_labels.txt
> +#numbers.Label keys as well as label values cannot exceed 63 characters each.
typo: `numbers.Label`

2020-08-19 23:21 UTC, rjmco commented on tb-marketplace/tb-config-creator/tb-config-creator
> +custom_labels_path="tb-gcp-tr/landingZone/no-itop/custom_labels.txt"
This will change with `custom_labels.txt`'s new file location.

2020-08-20 09:53 UTC, rjmco requested changes

2020-08-20 09:53 UTC, rjmco commented on tb-marketplace/tb-config-creator/tb-config-creator
> +custom_labels_path="tb-gcp/tb-marketplace/tb-config-creator/custom_labels.txt"
Tests fail if `tb-config-creator` is run from any other directory other than `tb-gcp`. To avoid this...

since `custom_labels.txt` is on the same directory as `tb-config-creator` script you can use the following to make sure that we can run `tb-config-creator` from anywhere in the filesystem.

```
 custom_labels_path="$(dirname ${BASH_SOURCE[0]})/custom_labels.txt"
```

2020-08-20 09:53 UTC, rjmco commented on tb-marketplace/tb-config-creator/tb-config-creator
> +find ${path}/tb-marketplace/tb-dep-manager -name test_config.yaml -exec sed -i "s/created_by:.*/created_by: '${ACTIVE_ACCOUNT}'/" '{}' \;
Tests fail if `tb-config-creator` is run from any other directory other than `tb-gcp`. To avoid this...

you can use the following to make sure that we can run `tb-config-creator` from anywhere in the filesystem.

```
sed -i "s/created_by:.*/created_by: '${ACTIVE_ACCOUNT}'/" $(dirname ${BASH_SOURCE[0]})/../tb-marketplace/tb-dep-manager/test_config.yaml
```

2020-08-20 11:49 UTC, rjmco approved these changes
LGTM.

2020-08-20 11:50 UTC, merged